---
    - name: Get Vector CentOS package
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}.rpm"
      when: ansible_distribution == "CentOS"
      tags: vector
    - name: Get Vector Ubuntu package
      become: true
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "./vector-{{ vector_version }}.deb"
      when: ansible_distribution == "Ubuntu"
      tags: vector
    - name: Install vector CentOS package
      become: true
      ansible.builtin.yum:
        name:
          - vector-{{ vector_version }}.rpm
        disable_gpg_check: yes
        disablerepo: "*"
        enablerepo: "centos-stream-release,centos-stream-repos"
      when: ansible_distribution == "CentOS"
      tags: vector
    - name: Install vector Ubuntu package
      become: true
      ansible.builtin.apt:
        deb: ./vector-{{ vector_version }}.deb
      when: ansible_distribution == "Ubuntu"
      tags: vector
    - name: Change vector systemd unit CentOS
      become: true
      ansible.builtin.template:
        src: vector.service.j2
        dest: /usr/lib/systemd/system/vector.service
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        backup: true
      when: ansible_distribution == "CentOS"
      tags: vector
    - name: Change vector systemd unit "Ubuntu"
      become: true
      ansible.builtin.template:
        src: vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        backup: true
      when: ansible_distribution == "Ubuntu"
      tags: vector
    - name: Apply vector template
      become: true
      ansible.builtin.template:
        src: vector.yml.j2
        dest: "{{ vector_config_dir }}/vector.yml"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        validate: vector validate --no-environment --config-yaml %s
      #notify: Start Vector service
      tags: vector
    - name: Is the vector config ready
      file:
        dest: "{{ vector_config_dir }}/vector.yml"
      notify: Start Vector service
      become: true
